### PR TITLE
Update the lesson with recent developments

### PR DESCRIPTION
**Pull request by bpurinton**
Resolves https://github.com/firstdraft/learn/issues/288

WIP Lesson: https://learn.firstdraft.com/lessons/246-how-to-write-a-lesson

**NOTE** Do not delete the WIP lesson above, as it is linked within the lesson as an example of the GitHub lesson writing flow.

I have removed all of the `Lorem ipsum` content, because the lesson was very long and very hard to read the important stuff with all that gobbledygook :)

### CODE REVIEW

**Comment by bpurinton** [comment]
Is this necessary? I _always_ forget to add the `^` but I've never had any issues:

```
- After the last item, leave a blank line and then an End Of Block (EOB) marker `^`.

^
```

I removed this note and all of the remaining `^` symbols on this commit: https://github.com/appdev-lessons/how-to-write-a-lesson/pull/1/commits/0baff10a58d0484b821139bfa0163ff245d49b79, and don't see any issues with the rendered lesson, so maybe we can remove this EOB note / requirement?

---

Not sure I understand what is desired in this note:

> **TODO** Modify the markdown parser to make adding children within li automatic.

**Comment by bpurinton** [comment]
I removed two sections ("Nested lists with code" and "Tables") on this commit: https://github.com/appdev-lessons/how-to-write-a-lesson/pull/1/commits/c7bd7acddbcc8bfe2f28a4d0c555607ace10195b that seemed vestigial from early dev days. I'm not sure we want those in here anymore, and whatever issues they were related to can be perhaps handled on some separate Learn PRs. 

We could have a section on "Tables" but probably better to just direct an author to some official docs, or [this part of the cheat-sheet](https://gist.github.com/raghubetina/a1b6e89e24a8c3acae6f0b63a1fd3323#tables)

**Comment by bpurinton** [comment]
I'm not sure what the intention of this section was, so I removed it on this commit: https://github.com/appdev-lessons/how-to-write-a-lesson/pull/1/commits/b1dcd0b8fbf4e9f0040d06dbc7bdedd653ab6539

```
#### No right answer (broken)

- Is there a pain point in your life that you might be able to solve with a small CRUD app?
- any
    - Okay! I have a note in my phone's Notes app dedicated to collecting pain points/app ideas. I recommend that you do something like that, too.
{: .broken #lion points="30" }
```

**Comment by bpurinton** [comment]
On this commit: https://github.com/appdev-lessons/how-to-write-a-lesson/pull/1/commits/bf9af5c5ba0bde4c1047d21854623e3444d20ab2

I removed this bit of code, since I've never seen this question type and am not sure that it is still relevant:

```
- Launch URL: https://lti-provider-example.herokuapp.com/lti_tool (required, no default)
- Button: Load TP Example in new tab (optional, default: "Load resource in new tab", if blank then assume iframe),
- Key: ...
- Secret: ...
{: .lti #elephant title="TP Example" points="30" answer="2" }
```

**Comment by raghubetina** [comment]
> Is this necessary? I _always_ forget to add the `^` but I've never had any issues:
> 
> ```
> - After the last item, leave a blank line and then an End Of Block (EOB) marker `^`.
> 
> ^
> ```
> 
> I removed this note and all of the remaining `^` symbols on this commit: [0baff10](https://github.com/appdev-lessons/how-to-write-a-lesson/commit/0baff10a58d0484b821139bfa0163ff245d49b79), and don't see any issues with the rendered lesson, so maybe we can remove this EOB note / requirement?
> 
> Not sure I understand what is desired in this note:
> 
> > **TODO** Modify the markdown parser to make adding children within li automatic.

I believe @jelaniwoods updated the Kramdown parser to handle this automatically. So, yes, this can be removed.

**Comment by raghubetina** [comment]
> I removed two sections ("Nested lists with code" and "Tables") on this commit: [c7bd7ac](https://github.com/appdev-lessons/how-to-write-a-lesson/commit/c7bd7acddbcc8bfe2f28a4d0c555607ace10195b) that seemed vestigial from early dev days. I'm not sure we want those in here anymore, and whatever issues they were related to can be perhaps handled on some separate Learn PRs.
> 
> We could have a section on "Tables" but probably better to just direct an author to some official docs, or [this part of the cheat-sheet](https://gist.github.com/raghubetina/a1b6e89e24a8c3acae6f0b63a1fd3323#tables)

Some of these were just there for "kitchen sink" purposes, to show all possibilities to authors & to help me write the CSS / verify that it was working. We could perhaps add a separate "kitchen sink" lesson for that purpose?

**Comment by raghubetina** [comment]
> I'm not sure what the intention of this section was, so I removed it on this commit: [b1dcd0b](https://github.com/appdev-lessons/how-to-write-a-lesson/commit/b1dcd0b8fbf4e9f0040d06dbc7bdedd653ab6539)
> 
> ```
> #### No right answer (broken)
> 
> - Is there a pain point in your life that you might be able to solve with a small CRUD app?
> - any
>     - Okay! I have a note in my phone's Notes app dedicated to collecting pain points/app ideas. I recommend that you do something like that, too.
> {: .broken #lion points="30" }
> ```

Do we currently have the ability to have a freeform question like the given example, where any answer gives full points? That was the intention of this, I think.

**Comment by raghubetina** [comment]
> On this commit: [bf9af5c](https://github.com/appdev-lessons/how-to-write-a-lesson/commit/bf9af5c5ba0bde4c1047d21854623e3444d20ab2)
> 
> I removed this bit of code, since I've never seen this question type and am not sure that it is still relevant:
> 
> ```
> - Launch URL: https://lti-provider-example.herokuapp.com/lti_tool (required, no default)
> - Button: Load TP Example in new tab (optional, default: "Load resource in new tab", if blank then assume iframe),
> - Key: ...
> - Secret: ...
> {: .lti #elephant title="TP Example" points="30" answer="2" }
> ```

I think this was my proposal for a new syntax for LTI resources, modeled on our quiz question syntax. The original syntax I came up with, modeled on the markdown for standard links, grew to be quite abstruse (IMO). Thoughts?

**Comment by raghubetina** [comment]
Responded to some of your notes, but LGTM!

**Comment by bpurinton** [comment]
> Some of these were just there for "kitchen sink" purposes, to show all possibilities to authors & to help me write the CSS / verify that it was working. We could perhaps add a separate "kitchen sink" lesson for that purpose?

I think we might eventually want this, but there is such myriad of markdown possibilities, I wonder if it's best to just point authors at some of our existing, bigger lessons. I'm adding a link to the [Contact Book Intro to DBs source code](https://raw.githubusercontent.com/appdev-lessons/contact-book-first-database/main/content.md) as the kitchen sink. Added the link on this commit: https://github.com/appdev-lessons/how-to-write-a-lesson/pull/1/commits/e6763b262469ad0da1fee0706a8b86c793ff7274

---

> Do we currently have the ability to have a freeform question like the given example, where any answer gives full points? That was the intention of this, I think.

Yes, we have that ability; [see here](https://learn.firstdraft.com/lessons/246-how-to-write-a-lesson#free_text:~:text=1%22%20answer%3D%22%5B1%5D%22%20%7D-,%E2%80%9Cany%20correct%20answer%E2%80%9D%3A%20If%20you%20want%20to%20accept%20any%20answer%2C%20you%20can%20use%20the%20any%20option%20in%20the%20answer%20array.%20For%20example%2C,-%7B%3A%20.free_text%20%23elephant%20title)

---

Side note, this issue: https://github.com/firstdraft/learn/issues/299 is apparently resolved, because I removed the markdown=1 on this commit: https://github.com/appdev-lessons/how-to-write-a-lesson/pull/1/commits/7ba5de19b61f9188416da24b63c44fc490e704bd and everything is rendering fine.

---

> I think this was my proposal for a new syntax for LTI resources, modeled on our quiz question syntax. The original syntax I came up with, modeled on the markdown for standard links, grew to be quite abstruse (IMO). Thoughts?

I see. I think we can stick with [the example LTI resource that is currently in there](https://learn.firstdraft.com/lessons/246-how-to-write-a-lesson#lti-button) and that we use in lessons. I think since this is very distinct from the quiz questions, we don't need to try and re-use that syntax.

**Pull request merged**
